docs_dir: ./../../docs
site_dir: ./site
site_name: SU Image Maker
use_directory_urls: false
repo_url: https://github.com/simpleunionspace/imagemaker/docs
nav:
    - Home:    README.md
    - Prototypes:  prototypes/README.md
    - Images:
        - base:    images/base/README.md
        - test:    images/test/README.md
        - fluentd: images/fluentd/README.md
        - nginx:   images/nginx/README.md
theme: readthedocs
