---

- name: bootstrap
  hosts: 127.0.0.1
  connection: local

  tasks:

    - include_tasks: deps_install.yaml

    - debug:
        msg: Platform name = {{ i_platform_name }}

    - include_tasks: deps_uninstall.yaml
